"""empty message

Revision ID: e69d894e64b8
Revises: a520c0354ada
Create Date: 2026-02-25 01:10:01.448554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69d894e64b8'
down_revision = 'a520c0354ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('population',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='post_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    # ### end Alembic commands ###
